---
version: "3.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:1.28.0
    container_name: plex
    network_mode: host
    restart: always
    environment:
      - PUID=1002
      - PGID=1002
      - VERSION=docker
#      - PLEX_CLAIM= 
    volumes:
      - /srv/data:/config
      - /srv/media:/srv/media
#      - /path/to/tvseries:/tv
#      - /path/to/movies:/movies
